stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t feathernet .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag feathernet $CI_REGISTRY_IMAGE/feathernet
    - docker push $CI_REGISTRY_IMAGE/feathernet

test:
  stage: test
  script:
    - nvidia-smi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/feathernet
    - CONTAINER_ID=$(docker run -d --gpus all $CI_REGISTRY_IMAGE/feathernet "make test-ci; sleep 10")
    - docker wait $CONTAINER_ID
    - docker logs $CONTAINER_ID
    - docker exec $CONTAINER_ID ls -la /usr/src/app
    - docker cp $CONTAINER_ID:/usr/src/app/coverage.xml coverage_report.xml
    - wget -O codecov.sh https://codecov.io/bash
    - chmod +x codecov.sh
    - ./codecov.sh -f coverage_report.xml
