stages:
  - check_runner
  - build
  - test

build:
  stage: build
  script:
    - docker build -t feathernet .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag feathernet $CI_REGISTRY_IMAGE/feathernet
    - docker push $CI_REGISTRY_IMAGE/feathernet

test:
  stage: test
  script:
    - nvidia-smi
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/feathernet
    - docker run --gpus all $CI_REGISTRY_IMAGE/feathernet make test

  after_script:
    - wget -O codecov.sh https://codecov.io/bash
    - chmod +x codecov.sh
    - ./codecov.sh
