name: Feathernet CI

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'  # Only on pushes to main.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/feathernet:latest

  test:
    needs: build-and-push
    runs-on: self-hosted
    container:
      image: ghcr.io/${{ github.repository_owner }}/feathernet:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Update dependencies
        run: poetry update

      - name: Run unit tests
        run: |
          coverage run -m unittest discover tests
          coverage report --fail-under 80

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
