name: Feathernet CI

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only on pushes to main.
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/feathernet:latest

  test:
    needs: build-and-push
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/feathernet:latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Update dependencies
        run: poetry update

      - name: Run compiler tests
        run: |
          coverage run --rcfile=.coveragerc_compiler -m unittest discover tests.compiler
          coverage report --fail-under 75

      - name: Run DL tests
        run: |
          coverage run --rcfile=.coveragerc_dl -m unittest discover tests.dl
          coverage report --fail-under 80
