name: Feathernet CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry --version
      - name: Install dependencies
        run: poetry install
      - name: Save Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Lint and format
        run: |
          poetry run make format
          poetry run make lint

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Restore Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Run compiler tests
        run: poetry run python -m unittest discover tests.compiler
      - name: Run DL tests
        run: poetry run python -m unittest discover tests.dl